branches:
  only:
    - master
    - develop
    - /^feature\/issue-\d+(-\S*)?$/
    - "/^release\\/\\d+\\.\\d+(\\.\\d+)?$/"

jobs:
  include:
    - stage: build_docs
      language: node_js
      node_js:
        - "12"
      before_script:
        - npm install -g @redocly/openapi-cli && npm install -g redoc-cli
        - npm install -g @ga4gh/gh-openapi-docs@0.2.2-rc3
      script:
        - gh-openapi-docs
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: true
        github-token: $GITHUB_TOKEN
        on:
          all_branches: true

    - stage: validate_spec
      jdk:
        - openjdk11
      env:
        - URL_START=https://raw.githubusercontent.com/ga4gh-rnaseq/schema/gh-pages/
        - URL_END=openapi.yaml
      before_install:
        - git clone --branch=v1.1.0 https://github.com/mcupak/oas-validator.git
      script:
        - source ci/set-url.sh
        - echo "${URL_START}${URL_BRANCH}${URL_END}"
        - ./oas-validator/validate.sh "${URL_START}${URL_BRANCH}${URL_END}"
